
name: Checkmarx One Scan
on:
  push:
    branches:
      - feature/187
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkmarx One CLI Action
        uses: checkmarx/ast-github-action@main #Github Action version
        with:
          base_uri: https://sng.ast.checkmarx.net/
          cx_tenant: sng_partners
          cx_client_id: ${cx_client_ID}
          cx_client_secret: ${CX_Client_Secret}
     
