
name: Checkmarx One Scan
on:
  push:
    branches:
      - feature/187
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkmarx One github Action
        uses: checkmarx/ast-github-action@main #Github Action version
        with:
          base_uri: https://sng.ast.checkmarx.net/
          cx_tenant: sng_partners
          cx_client_id: ${{cx_client_ID}}
          cx_client_secret: ${{CX_Client_Secret}}
           # Select a Checkmarx Project Name
          project_name: ${{ github.repository }}
           # Branch name
          branch: ${{ github.head_ref || github.ref }}
          # GitHub API Token
          github_token: ${{ github.token }}
          # Additional parameters for AST scan

          repo_name: ${{ github.event.repository.name }}
          # Organization name to create the Pr comment
          namespace:  ${{ github.repository_owner }}
          # Pr Number of the pull request that needs the decoration
          pr_number:  ${{ github.event.number }}
